# Generated by Django 5.0.7 on 2024-10-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_subcounty_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='GPS Coordinates Latitude')),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='GPS Coordinates Longitude')),
                ('gps_altitude', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='GPS Coordinates Altitude')),
                ('gps_precision', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='GPS Coordinates Precision')),
                ('cooperative_photo', models.ImageField(blank=True, null=True, upload_to='cooperatives/photos/')),
                ('organization_type', models.CharField(blank=True, choices=[('sacco', 'SACCO'), ('fpo', 'FPO'), ('other', 'Other')], max_length=255, null=True)),
                ('registration_status', models.CharField(blank=True, choices=[('registered', 'Registered'), ('not', 'Not Registered')], max_length=255, null=True)),
                ('registration_number', models.CharField(max_length=25, unique=True)),
                ('registration_date', models.DateField()),
                ('registered_office_address', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('is_automated', models.BooleanField(default=False)),
                ('common_bond', models.CharField(blank=True, choices=[('agpr', 'Agricultural Production'), ('empl', 'Common Employer'), ('fish', 'Fisheries'), ('real', 'Interest in Real Estate and Housing'), ('tran', 'Interest in the Transport Sector'), ('live', 'Livestock Production'), ('mark', 'Marketing'), ('local', 'Same Locality'), ('econo', 'Shared Economic Interest'), ('faith', 'Shared Faith'), ('other', 'Other Common Bond')], max_length=255, null=True)),
                ('contact_person_name', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('contact_person_role', models.CharField(blank=True, choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('bookkeeper', 'Book Keeper'), ('other', 'Other')], max_length=255, null=True)),
                ('contact_person_other_role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Please Specify Other Role')),
                ('contact_person_mobile', models.CharField(max_length=15, verbose_name='Contact Person Mobile Number')),
                ('contact_person_email', models.EmailField(max_length=254, verbose_name='Contact Person Email Address')),
                ('current_total_membership', models.PositiveIntegerField(verbose_name='Membership')),
                ('previous_year_membership', models.PositiveIntegerField(verbose_name='Previous Year Membership')),
                ('institutional_membership', models.PositiveIntegerField(verbose_name='Institutional/Corporate Membership')),
                ('male_membership', models.PositiveIntegerField(verbose_name='Male Membership')),
                ('female_membership', models.PositiveIntegerField(verbose_name='Female Membership')),
                ('male_youth_membership', models.PositiveIntegerField(verbose_name='Male Youth Membership')),
                ('female_youth_membership', models.PositiveIntegerField(verbose_name='Female Youth Membership')),
                ('indigenous_membership', models.PositiveIntegerField(blank=True, null=True, verbose_name='Indigenous Person Membership')),
                ('cig_federated_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of CIGs Federated')),
                ('cig_membership_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='CIG Members')),
                ('vmg_federated_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of VMGs Federated')),
                ('vmg_membership_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='VMG Members')),
                ('secretariate_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.county')),
                ('secretariate_sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subcounty')),
                ('secretariate_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ward')),
            ],
        ),
    ]
