# Generated by Django 5.0.7 on 2024-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='contact_person_other_role',
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Person Email Address'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='contact_person_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Person Mobile Number'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person Name'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='current_total_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='female_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Female Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='female_youth_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Female Youth Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='GPS Coordinates Altitude'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Coordinates Latitude'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Coordinates Longitude'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='gps_precision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='GPS Coordinates Precision'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='institutional_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Institutional/Corporate Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='is_automated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='male_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Male Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='male_youth_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Male Youth Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='previous_year_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous Year Membership'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='registered_office_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
