# Generated by Django 5.0.7 on 2024-10-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_dashboards_loansissued_loanspaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loansissued',
            name='sacco_code',
        ),
        migrations.AddField(
            model_name='loansissued',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative'),
        ),
        migrations.AlterField(
            model_name='bookkeeperregister',
            name='course_considered_for_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('national', 'National'), ('county', 'County'), ('sp', 'Service Provider'), ('fa', 'Funding Agency'), ('os', 'Other Stakeholders')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
