# Generated by Django 5.0.7 on 2024-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_remove_loansissued_sacco_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountsdisbursedtoorganisations',
            name='grant_type',
            field=models.CharField(blank=True, choices=[('Inclusion Grant', 'Inclusion Grant'), ('Matching Grant', 'Matching Grant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookkeeperregister',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('Below 5000', 'Below 5,000'), ('5000-10000', '5,000 – 10,000'), ('10001-15000', '10,001 – 15,000'), ('15001-20000', '15,001 – 20,000'), ('20001-25000', '20,001 – 25,000'), ('25001-50000', '25,001 – 50,000'), ('50001-100000', '50,001 – 100,000'), ('100001-150000', '100,001 – 150,000'), ('150000+', '150,000+')], default='5000-10000', max_length=20, null=True),
        ),
    ]
