# Generated by Django 5.0.7 on 2024-10-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_alter_bookkeeperregister_book_keeper_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='registration_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
